apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  labels:
    name: supplier-service
    app: supplier-app

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8010
  selector:
    name: supplier-pod
    app: supplier-app